# -*- coding: utf-8 -*-
"""Sistema Inteligente de Transporte: Búsqueda Heurística y Reglas Lógicas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10cs4xxW7DI92P3YFVg33ImJinsW5j6HP

# Caso de Prueba 1: Ruta Estándar (Origen: Estación A -> Destino: Estación F)
Este es el escenario principal donde el algoritmo evalúa múltiples caminos intermedios y selecciona la ruta más corta combinando las reglas lógicas del grafo y los valores heurísticos.
"""

import heapq

# Base de conocimiento (Reglas lógicas del sistema de transporte)
sistema_transporte = {
    'A': {'B': 5, 'C': 8},
    'B': {'A': 5, 'D': 6, 'E': 9},
    'C': {'A': 8, 'D': 4},
    'D': {'B': 6, 'C': 4, 'F': 5},
    'E': {'B': 9, 'F': 3},
    'F': {'D': 5, 'E': 3}
}

# Heurística (Estimación en línea recta hacia el destino F)
heuristica = {
    'A': 10, 'B': 7, 'C': 6, 'D': 4, 'E': 2, 'F': 0
}

def buscar_mejor_ruta(inicio, destino, grafo, heuristica):
    rutas_por_evaluar = []
    heapq.heappush(rutas_por_evaluar, (0, inicio))
    costo_real = {inicio: 0}
    ruta_previa = {inicio: None}

    while rutas_por_evaluar:
        _, estacion_actual = heapq.heappop(rutas_por_evaluar)

        if estacion_actual == destino:
            ruta_final = []
            while estacion_actual is not None:
                ruta_final.append(estacion_actual)
                estacion_actual = ruta_previa[estacion_actual]
            ruta_final.reverse()
            return ruta_final, costo_real[destino]

        for vecino, costo_viaje in grafo[estacion_actual].items():
            nuevo_costo = costo_real[estacion_actual] + costo_viaje
            if vecino not in costo_real or nuevo_costo < costo_real[vecino]:
                costo_real[vecino] = nuevo_costo
                costo_estimado_total = nuevo_costo + heuristica[vecino]
                heapq.heappush(rutas_por_evaluar, (costo_estimado_total, vecino))
                ruta_previa[vecino] = estacion_actual
    return None, 0

# Prueba 1
punto_inicio, punto_destino = 'A', 'F'
ruta, costo = buscar_mejor_ruta(punto_inicio, punto_destino, sistema_transporte, heuristica)
print(f"--- PRUEBA 1 ---")
print(f"Origen: {punto_inicio} | Destino: {punto_destino}")
print(f"Ruta óptima encontrada: {' -> '.join(ruta)}")
print(f"Costo total del viaje: {costo} unidades")

"""# Caso de Prueba 2: Ruta Corta Directa (Origen: Estación C -> Destino: Estación D)
En este caso, evaluamos un trayecto más corto dentro de la red de transporte para verificar cómo el sistema procesa nodos vecinos con conexiones directas
"""

# Prueba 2
punto_inicio, punto_destino = 'C', 'D'
ruta, costo = buscar_mejor_ruta(punto_inicio, punto_destino, sistema_transporte, heuristica)
print(f"\n--- PRUEBA 2 ---")
print(f"Origen: {punto_inicio} | Destino: {punto_destino}")
print(f"Ruta óptima encontrada: {' -> '.join(ruta)}")
print(f"Costo total del viaje: {costo} unidades")

"""# Caso de Prueba 3: Trayecto Alternativo Cruzado (Origen: Estación E -> Destino: Estación A)"""

# Prueba 3
punto_inicio, punto_destino = 'E', 'A'
ruta, costo = buscar_mejor_ruta(punto_inicio, punto_destino, sistema_transporte, heuristica)
print(f"\n--- PRUEBA 3 ---")
print(f"Origen: {punto_inicio} | Destino: {punto_destino}")
print(f"Ruta óptima encontrada: {' -> '.join(ruta)}")
print(f"Costo total del viaje: {costo} unidades")

"""# Código final"""

import heapq

# ====================================================================
# PARTE 1: CÓDIGO PRINCIPAL (Base de conocimiento y Algoritmo A*)
# ====================================================================

# Base de conocimiento: Grafo que representa las estaciones y los costos de viaje
sistema_transporte = {
    'A': {'B': 5, 'C': 8},
    'B': {'A': 5, 'D': 6, 'E': 9},
    'C': {'A': 8, 'D': 4},
    'D': {'B': 6, 'C': 4, 'F': 5},
    'E': {'B': 9, 'F': 3},
    'F': {'D': 5, 'E': 3}
}

# Heurística: Estimación del costo en línea recta desde cada estación hasta el destino final (F)
heuristica = {
    'A': 10, 'B': 7, 'C': 6, 'D': 4, 'E': 2, 'F': 0
}

def buscar_mejor_ruta(inicio, destino, grafo, heuristica):
    """
    Función principal del sistema inteligente que implementa el algoritmo A*
    para encontrar la ruta óptima entre dos estaciones.
    """
    rutas_por_evaluar = []
    heapq.heappush(rutas_por_evaluar, (0, inicio))
    costo_real = {inicio: 0}
    ruta_previa = {inicio: None}

    while rutas_por_evaluar:
        _, estacion_actual = heapq.heappop(rutas_por_evaluar)

        # Si llegamos al destino, reconstruimos el camino
        if estacion_actual == destino:
            ruta_final = []
            while estacion_actual is not None:
                ruta_final.append(estacion_actual)
                estacion_actual = ruta_previa[estacion_actual]
            ruta_final.reverse()
            return ruta_final, costo_real[destino]

        for vecino, costo_viaje in grafo[estacion_actual].items():
            nuevo_costo = costo_real[estacion_actual] + costo_viaje
            if vecino not in costo_real or nuevo_costo < costo_real[vecino]:
                costo_real[vecino] = nuevo_costo
                costo_estimado_total = nuevo_costo + heuristica[vecino]
                heapq.heappush(rutas_por_evaluar, (costo_estimado_total, vecino))
                ruta_previa[vecino] = estacion_actual

    return None, 0


# ====================================================================
# PARTE 2: CASOS DE PRUEBA (Ejecución y resultados para evidencias)
# ====================================================================

print("==================================================")
print("     EJECUCIÓN DE PRUEBAS - SISTEMA INTELIGENTE   ")
print("==================================================")

# --- PRUEBA 1 ---
inicio_1, destino_1 = 'A', 'F'
ruta_1, costo_1 = buscar_mejor_ruta(inicio_1, destino_1, sistema_transporte, heuristica)
print(f"\n[PRUEBA 1]")
print(f"Ruta evaluada: Desde la estación {inicio_1} hasta la estación {destino_1}")
print(f"Ruta óptima encontrada: {' -> '.join(ruta_1)}")
print(f"Costo total del trayecto: {costo_1} unidades")

# --- PRUEBA 2 ---
inicio_2, destino_2 = 'C', 'D'
ruta_2, costo_2 = buscar_mejor_ruta(inicio_2, destino_2, sistema_transporte, heuristica)
print(f"\n[PRUEBA 2]")
print(f"Ruta evaluada: Desde la estación {inicio_2} hasta la estación {destino_2}")
print(f"Ruta óptima encontrada: {' -> '.join(ruta_2)}")
print(f"Costo total del trayecto: {costo_2} unidades")

# --- PRUEBA 3 ---
inicio_3, destino_3 = 'E', 'A'
ruta_3, costo_3 = buscar_mejor_ruta(inicio_3, destino_3, sistema_transporte, heuristica)
print(f"\n[PRUEBA 3]")
print(f"Ruta evaluada: Desde la estación {inicio_3} hasta la estación {destino_3}")
print(f"Ruta óptima encontrada: {' -> '.join(ruta_3)}")
print(f"Costo total del trayecto: {costo_3} unidades")
print("\n==================================================")

"""# [PRUEBA 1] (Desde la estación A hasta la estación F):

Ruta óptima encontrada (A -> B -> D -> F): El algoritmo determinó que el camino más eficiente para ir de la estación inicial A hasta la estación final F es pasar por las estaciones intermedias B y D.

Costo total (16 unidades): Es la suma de los costos o distancias de cada tramo de ese recorrido específico.

[PRUEBA 2] (Desde la estación C hasta la estación D):

Ruta óptima encontrada (C -> D): Al evaluar un trayecto más corto y directo, el sistema identificó que la conexión es directa entre la estación C y la D sin necesidad de pasar por otros puntos.

Costo total (4 unidades): Representa el costo directo de ese único tramo.

[PRUEBA 3] (Desde la estación E hasta la estación A):

Ruta óptima encontrada (E -> B -> A): Demuestra la bidireccionalidad y flexibilidad del sistema al calcular rutas en sentido inverso (desde el extremo E hacia el inicio A), pasando por la estación B.

Costo total (14 unidades): La sumatoria del costo acumulado de ese trayecto de vuelta.


"""

import heapq
import networkx as nx
import matplotlib.pyplot as plt

# ====================================================================
# 1. BASE DE CONOCIMIENTO Y ALGORITMO A*
# ====================================================================

sistema_transporte = {
    'A': {'B': 5, 'C': 8},
    'B': {'A': 5, 'D': 6, 'E': 9},
    'C': {'A': 8, 'D': 4},
    'D': {'B': 6, 'C': 4, 'F': 5},
    'E': {'B': 9, 'F': 3},
    'F': {'D': 5, 'E': 3}
}

heuristica = {
    'A': 10, 'B': 7, 'C': 6, 'D': 4, 'E': 2, 'F': 0
}

def buscar_mejor_ruta(inicio, destino, grafo, heuristica):
    rutas_por_evaluar = []
    heapq.heappush(rutas_por_evaluar, (0, inicio))
    costo_real = {inicio: 0}
    ruta_previa = {inicio: None}

    while rutas_por_evaluar:
        _, estacion_actual = heapq.heappop(rutas_por_evaluar)

        if estacion_actual == destino:
            ruta_final = []
            while estacion_actual is not None:
                ruta_final.append(estacion_actual)
                estacion_actual = ruta_previa[estacion_actual]
            ruta_final.reverse()
            return ruta_final, costo_real[destino]

        for vecino, costo_viaje in grafo[estacion_actual].items():
            nuevo_costo = costo_real[estacion_actual] + costo_viaje
            if vecino not in costo_real or nuevo_costo < costo_real[vecino]:
                costo_real[vecino] = nuevo_costo
                costo_estimado_total = nuevo_costo + heuristica[vecino]
                heapq.heappush(rutas_por_evaluar, (costo_estimado_total, vecino))
                ruta_previa[vecino] = estacion_actual

    return None, 0


# ====================================================================
# 2. FUNCIÓN PARA GRAFICAR EL MAPA Y LA RUTA ÓPTIMA
# ====================================================================

def visualizar_ruta(grafo, ruta_optima, titulo):
    G = nx.Graph()

    # Agregar aristas y costos al grafo visual
    for nodo, vecinos in grafo.items():
        for vecino, costo in vecinos.items():
            G.add_edge(nodo, vecino, weight=costo)

    # Coordenadas fijas para que el mapa de estaciones se vea ordenado
    posiciones = {
        'A': (0, 2),
        'B': (2, 3),
        'C': (1, 0),
        'D': (3, 1),
        'E': (4, 3),
        'F': (5, 2)
    }

    plt.figure(figsize=(8, 5))

    # Dibujar todas las estaciones y conexiones base
    nx.draw_networkx_nodes(G, posiciones, node_size=700, node_color='lightblue')
    nx.draw_networkx_labels(G, posiciones, font_size=12, font_weight='bold')

    # Etiquetas de los costos en las líneas
    etiquetas_aristas = nx.get_edge_attributes(G, 'weight')
    nx.draw_networkx_edge_labels(G, posiciones, edge_labels=etiquetas_aristas)

    # Dibujar todas las conexiones grises
    nx.draw_networkx_edges(G, posiciones, edge_color='gray', width=2)

    # Si hay una ruta óptima, resaltarla en color VERDE y con líneas gruesas
    if ruta_optima:
        pares_ruta = list(zip(ruta_optima[:-1], ruta_optima[1:]))
        nx.draw_networkx_edges(G, posiciones, edgelist=pares_ruta, edge_color='green', width=4)
        nx.draw_networkx_nodes(G, posiciones, nodelist=ruta_optima, node_size=700, node_color='lightgreen')

    plt.title(titulo, fontsize=14, fontweight='bold')
    plt.axis('off')
    plt.show()


# ====================================================================
# 3. EJECUCIÓN DE LAS PRUEBAS CON SALIDA GRÁFICA
# ====================================================================

print("=== GENERANDO VISUALIZACIONES GRÁFICAS DE LAS PRUEBAS ===\n")

# Prueba 1
ruta_1, costo_1 = buscar_mejor_ruta('A', 'F', sistema_transporte, heuristica)
print(f"PRUEBA 1: A -> F | Ruta: {' -> '.join(ruta_1)} | Costo: {costo_1}")
visualizar_ruta(sistema_transporte, ruta_1, "Prueba 1: Ruta Óptima de A hasta F")

# Prueba 2
ruta_2, costo_2 = buscar_mejor_ruta('C', 'D', sistema_transporte, heuristica)
print(f"PRUEBA 2: C -> D | Ruta: {' -> '.join(ruta_2)} | Costo: {costo_2}")
visualizar_ruta(sistema_transporte, ruta_2, "Prueba 2: Ruta Óptima de C hasta D")

# Prueba 3
ruta_3, costo_3 = buscar_mejor_ruta('E', 'A', sistema_transporte, heuristica)
print(f"PRUEBA 3: E -> A | Ruta: {' -> '.join(ruta_3)} | Costo: {costo_3}")
visualizar_ruta(sistema_transporte, ruta_3, "Prueba 3: Ruta Óptima de E hasta A (Inverso)")